/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eveinventorymanager;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Connor
 */
public class NewAlertFrame extends javax.swing.JFrame {
    
    AlertFrame parent;
    
    /**
     * Creates new form NewAlertFrame
     */
    public NewAlertFrame(AlertFrame parent) {
        initComponents();
        this.parent = parent;
        this.setIconImage(parent.getIconImage());
        itemComboBox.setModel(new DefaultComboBoxModel(parent.parent.accountList.toNameArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        badNameLabel = new javax.swing.JLabel();
        itemLabel = new javax.swing.JLabel();
        itemComboBox = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        itemLabel1 = new javax.swing.JLabel();
        itemLabel2 = new javax.swing.JLabel();
        itemLabel3 = new javax.swing.JLabel();
        valueComboBox = new javax.swing.JComboBox<>();
        conditionComboBox = new javax.swing.JComboBox<>();
        amountSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        badNameLabel.setForeground(new java.awt.Color(255, 0, 0));
        badNameLabel.setText(" ");

        itemLabel.setText("Value");

        itemComboBox.setEditable(true);
        itemComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        itemComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComboBoxActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        itemLabel1.setText("Item");

        itemLabel2.setText("Condition");

        itemLabel3.setText("Amount");

        valueComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity of", "Value of"}));
        valueComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueComboBoxActionPerformed(evt);
            }
        });

        conditionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "is above", "is below"}));
        conditionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conditionComboBoxActionPerformed(evt);
            }
        });

        amountSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 10.0d));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(badNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(itemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valueComboBox, 0, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itemComboBox, 0, 100, Short.MAX_VALUE)
                            .addComponent(itemLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(conditionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itemLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itemLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(amountSpinner))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemLabel)
                    .addComponent(itemLabel1)
                    .addComponent(itemLabel2)
                    .addComponent(itemLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conditionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void itemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComboBoxActionPerformed
        if(Functions.itemID((String)itemComboBox.getSelectedItem())==0) {
            badNameLabel.setText("ITEM NAME NOT RECOGNIZED");
        } else {
            badNameLabel.setText(" ");
        }
    }//GEN-LAST:event_itemComboBoxActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String name = (String)itemComboBox.getSelectedItem();
        int ID = Functions.itemID(name);
        int value = valueComboBox.getSelectedIndex()*2;
        int condition = conditionComboBox.getSelectedIndex();
        double amount = (double)amountSpinner.getValue(); 
        if(ID!=0) {
            parent.parent.alertList.add(new ItemCheck(ID,value+condition,amount));
            parent.refreshTable();
        } else {
            JOptionPane.showMessageDialog(this,"Error:\nYou have entered invalid arguments.\nPlease ensure the name you used is correct.\nIf you are unsure, check the name in-game.");
        }
        cancelButtonActionPerformed(evt);
    }//GEN-LAST:event_okButtonActionPerformed

    private void valueComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueComboBoxActionPerformed

    private void conditionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conditionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conditionComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JLabel badNameLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> conditionComboBox;
    private javax.swing.JComboBox<String> itemComboBox;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JLabel itemLabel1;
    private javax.swing.JLabel itemLabel2;
    private javax.swing.JLabel itemLabel3;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> valueComboBox;
    // End of variables declaration//GEN-END:variables
}
